[Test]
Test=1

[SFIS]
IP=10.5.10.18
Port=21347
Line=Omron

[Setting]
# 扫码回车触发测试，1：打开；0：关闭
Enter2Test=1
# 测试最大等待时间
WaitTimeOut=500

[SNRule]
# 场内SN条码长度，-1:表示不卡关长度
Length=-1
# 场内SN条码前n码固定文本比对，为空时不对比前n码
StartsWith=123

[Global]
# 标准间条码，用于屏蔽测试前的过站检查
OKSN=123

[Address]
# 客户测试系统exe文件路径  需要修改
SystemToolPath=C:\OC_WIN\OC_WIN.exe

# 本程序的测试本地测试log存放路径
TemppTestLogDirectoryPath=./TempLog

# 本程序的测试Server log存放路径
TestLogDirectoryPath=./Log

# 客户测试系统的Log 生成路径  需要修改
SystemTempLogPath=C:\OC_WIN\Logs

# 客户测试系统的Log 转存路径
SystemLogPath=./SystemLog

[ErrorCode]
DefaultCode=AAAAAA
Error_R1=BBBBBB



[TargetLine]
# 默认目标行数（当产品号未匹配时使用）
Default=100
# 可按产品号单独指定，格式：ProductNo=行数
# 例如：
# 4444444-424223MU00005=120
# 123456-789=90
